Adapting BBHx plugin to use higher order modes.
gwastro/BBHX-waveform-model pull request #2
Opened 2023-12-08 10:23 UTC by ConWea

Added two separate approximants depending on if the user would like only the 22 mode (BBHX_PhenomD) or any other mode (BBHX_PhenomHM). Also renamed the actual plugin file as to not cause confusion regarding what mode content the file gives.

2023-12-11 10:00 UTC, WuShichao commented
@ConWea Thanks! I will review this PR tomorrow.

2023-12-12 17:31 UTC, WuShichao reviewed
There are three original functions only support (2,2) mode: `chirptime`, `imr_duration`, and `interpolated_tf`. For the `imr_duration`, it's easy to update with HM wavform. For the other two, I don't know if there are any equations to get each mode's time-frequency track.

2023-12-12 17:31 UTC, WuShichao commented on BBHX_Phenom.py
> +    compress = True #  If True, combine harmonics into single channel waveforms. (Default: True)
@ConWea If we need to estimate each mode's contribution (such as calculating each mode's SNR or likelihood), I guess it would be better to allow our plugin to return them separately, right?

2023-12-12 17:31 UTC, WuShichao commented on setup.py
> +                    "pycbc.waveform.length":"BBHX_PhenomD=BBHX_Phenom:imr_duration"},
@ConWea Can you also update this `imr_duration` function to allow the use of IMRPhenomHM? Currently, it only uses `imrphenomd_length_in_time` from PyCBC.

2023-12-12 17:31 UTC, WuShichao commented on BBHX_Phenom.py
> +    # Using findchirp_chirptime in PyCBC to calculate
@ConWea For the time-frequency track calculation here (also the `chirptime` function in the plugin), it only supports (2,2) mode, but I guess it will not affect too much. What do you think? @ahnitz

2023-12-13 15:48 UTC, ConWea commented on BBHX_Phenom.py
> +    compress = True #  If True, combine harmonics into single channel waveforms. (Default: True)
Yes but you would have to just ask for a single mode at a time. BBHx has the capability to return all modes separately in one dict, but this way, no matter how many you ask for it will compress them into one tdi stream.

2023-12-13 15:50 UTC, ConWea commented on setup.py
> +                    "pycbc.waveform.length":"BBHX_PhenomD=BBHX_Phenom:imr_duration"},
Good spot! Will do this now.

2023-12-13 16:26 UTC, WuShichao commented on BBHX_Phenom.py
> +    compress = True #  If True, combine harmonics into single channel waveforms. (Default: True)
@ConWea I know when setting `compress = True`, it will combine all modes' waveform. Can you give me an example of how to access the (3,3) model by using the current PR?

2023-12-13 17:34 UTC, ConWea commented on BBHX_Phenom.py
> +    compress = True #  If True, combine harmonics into single channel waveforms. (Default: True)
So you have to use the approximant "BBHX_PhenomHM". That sets `run_phenomd=False`. The whatever mode_array you pass to the function will contain the mode information requested. So with the other required parameters, and:

```
params['approximant'] = 'IMRPhenomHM'
params['mode_array'] = '33'
```

would produce the tdi response for the 33 mode only. Say you wanted mode_array = "22 33", it would return the combined waveform of the 22 and 33 modes.

2023-12-14 14:34 UTC, ConWea commented on BBHX_Phenom.py
> +    # Using findchirp_chirptime in PyCBC to calculate
@WuShichao Currently when using the multi_signal model, only one mode is every called at a time. So I don't know if these functions still hold when computing those. However, I assume this would be a problem when producing the injection? Where you ask for multiple modes combined into one tdi channel

2023-12-15 10:44 UTC, ConWea commented on setup.py
> +                    "pycbc.waveform.length":"BBHX_PhenomD=BBHX_Phenom:imr_duration"},
Added the `imr_duration` change in the lates commit

2023-12-15 11:00 UTC, ConWea commented
I accidentally undid some commits and have added them back with the last two commits.

2023-12-20 14:18 UTC, WuShichao commented on BBHX_Phenom.py
> +    # Using findchirp_chirptime in PyCBC to calculate
@ConWea For the PE, even if only one mode is every called at a time, the PN equations behind of these functions are still valid for (2,2), we need to find the corresponding equations for HM.

2023-12-20 17:01 UTC, ConWea commented on BBHX_Phenom.py
> +    # Using findchirp_chirptime in PyCBC to calculate
Okay, thank you @WuShichao. Do you have an idea of what needs to be done here @ahnitz ?

2024-02-02 10:41 UTC, spxiwh commented
Can we converge on this. It is important to be able to use the HM version of the code.

@mj-will Can you work with Connor if you've also got a version of this in play?

2024-02-02 11:21 UTC, ConWea commented
@spxiwh I've added some other control support to allow users to change variables in the BBHx code. For example, we've found that the length parameter can be really important (chooses points of interpolation) when recovering with HoM. Would it be easier to close this PR and open a fresh one? 

I know the outstanding questions are the `interpolated_fd` and `chirptime` functions are 22 mode specific. So are there equivalent functions for other modes?

2024-02-02 12:03 UTC, mj-will commented
> @mj-will Can you work with Connor if you've also got a version of this in play?

@spxiwh sure, I've been using a much hackier version since I knew Connor has this version in the works. Looking at these changes, it should be trivial to switch to this version once it's ready.

2024-02-02 12:07 UTC, mj-will commented on BBHX_Phenom.py
> +        return _bbhx_fd(run_phenomd=False, **kwargs)
If I'm following the logic correctly, I think this means there isn't a default `mode_array` for PhenomHM. In most cases, I think users would assume setting `approximant='BBHX_PhenomHM'` would enable all the modes, so I'd suggest adding a default. Maybe something like:

```suggestion
    elif kwargs['approximant'] == "BBHX_PhenomHM":
        if 'mode_array' not in kwargs:
            kwargs['mode_array'] = [(2, 2), (2, 1), (3, 3), (3, 2), (4, 4), (4, 3)]
        return _bbhx_fd(run_phenomd=False, **kwargs)
```

2024-02-02 12:19 UTC, mj-will commented on BBHX_Phenom.py
> +    # Using findchirp_chirptime in PyCBC to calculate
I'm pretty sure this chirp time functions is based on what is used for PhenomD/X, so these links may be useful:

- Function in PhenomD: https://git.ligo.org/lscsoft/lalsuite/-/blob/master/lalsimulation/lib/LALSimIMRPhenomD.c#L597
- Function in PhenomX: https://git.ligo.org/lscsoft/lalsuite/-/blob/master/lalsimulation/lib/LALSimIMRPhenomX.c#L408

These also include spins, so they're one step closer to what you need but they don't include HoM.

2024-02-05 10:16 UTC, ConWea commented on BBHX_Phenom.py
> +        return _bbhx_fd(run_phenomd=False, **kwargs)
@mj-will  If no modes are given to PhenomHM, by default, BBHx returns all available modes. So that is why we don't enforce here what the modes should be because you want to be able to call individual modes from PhenomHM as well as potentially a few modes at once.

2024-02-05 10:29 UTC, ConWea commented on BBHX_Phenom.py
> +    # Using findchirp_chirptime in PyCBC to calculate
Okay, thank you @mj-will

2024-02-06 12:00 UTC, ConWea commented on BBHX_Phenom.py
> +        return _bbhx_fd(run_phenomd=False, **kwargs)
Just added a raise exception if the mode_arrary is not given when using PhenomHM

2024-02-06 12:02 UTC, mj-will commented on BBHX_Phenom.py
> +        return _bbhx_fd(run_phenomd=False, **kwargs)
I'm not sure about this change, it means the user always has to specify the mode array. Normally, if I ask for an approximant, I'd expect it to have some sort of default for the modes (which I think is what you had before)

2024-02-06 12:11 UTC, ConWea commented on BBHX_Phenom.py
> +        return _bbhx_fd(run_phenomd=False, **kwargs)
Yeah I see what you mean. My logic here was making sure that the user always knows what modes they're getting back by forcing them to specify the mode content. In the multi_signal model, I specify for each submodel what mode_array it is. If somebody doesn't do this they could potentially run a submodel with all default modes and it'll mess the inference up.

2024-02-06 12:13 UTC, ConWea commented on BBHX_Phenom.py
> +        return _bbhx_fd(run_phenomd=False, **kwargs)
Maybe there should be a message given in the log to say "Modes set to default values of 'blah'" ? Then they can trace it back easily?

2024-02-07 09:55 UTC, mj-will commented on BBHX_Phenom.py
> +        return _bbhx_fd(run_phenomd=False, **kwargs)
I get that in the context of the multi_signal model, but I think in general you'd expect a default for normal use, like when you use the standard IMRPhenomXPHM for ground-based inference.

I think you could have a onetime log statement/warning but I would personally avoid something like that being printed every time. Though I don't know what the default approach is for these sorts of things in pycbc, so that might be a question for @ahnitz or @spxiwh

2024-02-16 13:28 UTC, ConWea commented on BBHX_Phenom.py
> +        return _bbhx_fd(run_phenomd=False, **kwargs)
@mj-will I've added your requested change!

2024-02-27 20:27 UTC, ahnitz commented
@ConWea @mj-will What's the status of this patch?

2024-02-28 08:41 UTC, mj-will commented
> @ConWea @mj-will What's the status of this patch?

@ahnitz I believe the main that's left to address is [this discussion](https://github.com/gwastro/BBHX-waveform-model/pull/2#discussion_r1477970144) about the chirp time.

From the discussion on slack, I think @WuShichao found the equations for doing this but I'm not sure if that's a change that should be made to BBHx or the pycbc function.

2024-02-28 09:05 UTC, WuShichao commented
@ahnitz @mj-will @ConWea For the HM waveform (especially for SOBHB), that `log_mf_min` passed to `get_waveform_genner` is important. In order to get the correct `log_mf_min`, we need to take HM into account.

2024-02-28 09:33 UTC, mj-will commented
> @ahnitz @mj-will @ConWea For the HM waveform (especially for SOBHB), that `log_mf_min` passed to `get_waveform_genner` is important. In order to get the correct `log_mf_min`, we need to take HM into account.

I completely agree, I thinki my questions is whether we should `findchirp_chirptime` or implement this plugin.

2024-03-01 13:08 UTC, WuShichao commented
> > @ahnitz @mj-will @ConWea For the HM waveform (especially for SOBHB), that `log_mf_min` passed to `get_waveform_genner` is important. In order to get the correct `log_mf_min`, we need to take HM into account.
> 
> I completely agree, my questions is whether we should update `findchirp_chirptime` or implement this plugin.

Yes, but the `interpolated_tf` in the plugin still need some updates for that. Maybe @ahnitz can give some advice.

2024-03-01 13:34 UTC, mj-will commented on BBHX_Phenom.py
> +             min_f=False, **params):
I noticed `min_f` is `False` by default, this means this change is not backwards compatible as existing codes won't have this set and minimum frequency won't be set. Was the reason for defaulting to `False`?

2024-03-01 13:35 UTC, mj-will commented on BBHX_Phenom.py
> +                err_msg = f"Input 'f_lower' is lower than the value calculated from 't_obs_start'."
This error is never raised or used to issue a warning

2024-03-01 13:36 UTC, mj-will commented
@WuShichao I see what you mean. If I follow correctly, this is setting `t_obs_start` such that it includes the `f_lower` specified, so I think the correct logic would be to use the mode that gives the lowest frequency? What do you think?

2024-03-01 13:52 UTC, ConWea commented on BBHX_Phenom.py
> +             min_f=False, **params):
@mj-will Yes so I did this because currently I wanted BBHx to give me the frequencies it thinks it needs instead of doing what Shichao and Alex implemented. We've found that for HoMs the interpolation and frequencies that are chosen are really important. 

Happy to set this to True

2024-03-01 13:54 UTC, ConWea commented
> @ConWea @mj-will What's the status of this patch?

I am currently looking at what has been discussed regarding the chirptime function and how we can use the 22 frequencies to compute the other modes. But to be honest I am confused about it and not sure two implement it.

2024-03-03 20:21 UTC, WuShichao commented
> @WuShichao I see what you mean. If I follow correctly, this is setting `t_obs_start` such that it includes the `f_lower` specified, so I think the correct logic would be to use the mode that gives the lowest frequency? What do you think?

"this is setting t_obs_start such that it includes the f_lower specified" is not that right, `t_obs_start` set by users in the PE config file will determine the `f_min` by using the `f_min = tf_track(t_obs_start)`, while "the correct logic would be to use the mode that gives the lowest frequency" is correct. @ConWea So what we need to do is update `chirptime` and `interpolated_tf` to support HMs. `f_min` will be the lowest frequency at `t_obs_start` among all the HMs. Note that `interpolated_tf` just fits one mode at the moment.

2024-03-03 20:22 UTC, WuShichao requested changes
Please see my comments in other places.

2024-03-03 20:22 UTC, WuShichao commented on BBHX_Phenom.py
> +    if direct == 'True' or direct == True:
Why `direct == 'True' or direct == True`?

2024-03-03 20:22 UTC, WuShichao commented on setup.py
> +                    "pycbc.waveform.length":"BBHX_PhenomD=BBHX_Phenom:imr_duration"},
Do you also need to add `"BBHX_IMRPhenomHM=BBHX_Phenom:imr_duration"`?

2024-04-09 11:42 UTC, mj-will commented on BBHX_Phenom.py
> +            f_min = np.float64(params['f_lower']) # in Hz
I don't entirely follow the logic here, but should `f_min`  be used in `chirptime`?

2024-04-17 12:12 UTC, WuShichao commented on BBHX_Phenom.py
> +            f_min = np.float64(params['f_lower']) # in Hz
This checks if the `f_lower` input by users is valid or not.

2024-05-14 20:22 UTC, WuShichao commented
Do we need to close this?

2024-08-22 12:41 UTC, WuShichao commented
@mj-will suggests that we can close this.

2024-08-22 12:41 UTC, closed without merging