Add support for HoM
gwastro/BBHX-waveform-model pull request #7
Opened 2024-05-07 09:35 UTC by mj-will

Add support for HoM.

This MR supersedes https://github.com/gwastro/BBHX-waveform-model/pull/2, since Connor is writing up and I'm going to try and get this change in for the various projects that need it.

## To-Do

- [ ] Plots described in https://github.com/ConWea/BBHX-waveform-model/pull/2

2024-05-08 14:49 UTC, mj-will commented
@spxiwh I've looked at how BBHx is implemented and I don't think it automatically works out a starting frequency anywhere in the code, instead it always uses `mf_min` (see https://github.com/mikekatz04/BBHx/blob/master/bbhx/waveforms/phenomhm.py#L107).

So I think we can just follow the Phenom convention and set the minium frequency based on highest m mode. For reference, do you know where this is defined in LAL?

2024-05-08 14:55 UTC, spxiwh commented
PyCBC does this here:

https://github.com/gwastro/pycbc/blob/master/pycbc/waveform/waveform.py#L1056

to the best of my knowledge LAL does not do this [properly], if generating f-domain waveforms in the time domain.

2024-05-12 21:47 UTC, WuShichao requested changes
Thanks for updating. I have added two new comments, please check.

2024-05-12 21:47 UTC, WuShichao commented on BBHX_Phenom.py
> +                m_mode=max_m_mode,
@mj-will Thanks for the latest changes! According to your time-frequency track plot (I believe the y-axis is in the unit of Hz), for a given `t_obs_start`, you need to set `f_min` to be the lowest frequency among all the modes. But here you are using the `max_m_mode`, so the highest frequency. Can you do two further checks for SMBHB and SOBHB: adding the Q-transform plot for the real BBHx TDI-HM waveform, and plotting the theoretical time-frequency tracks on top of it, then drawing a vertical line to indicate the given `t_obs_start`, similar to this plot (from 10.1103/PhysRevD.102.043015), you can use noise-free data to clearly show all the modes: 
![image](https://github.com/gwastro/BBHX-waveform-model/assets/6574526/b3ef4b17-6ca4-47cc-b5f4-cacb30f23a0a)

2024-05-12 21:47 UTC, WuShichao commented on BBHX_Phenom.py
> +    if log_mf_min is None:
Why `log_mf_min` can be `None`?

2024-05-12 21:53 UTC, WuShichao commented on BBHX_Phenom.py
> +    if log_mf_min is None:
It would be better always to give `log_mf_min`, otherwise BBHx will use its default value for it, that one is only suitable for SMBHB, and users may not even know this detail.

2024-05-13 08:14 UTC, mj-will commented on BBHX_Phenom.py
> +                m_mode=max_m_mode,
@WuShichao I went back and forth on whether to use the max or min m mode, but after some discussion with @spxiwh we concluded we should use the max m mode so we're consistent with what PyCBC does, see https://github.com/gwastro/pycbc/blob/master/pycbc/waveform/waveform.py#L1056 and https://github.com/gwastro/BBHX-waveform-model/pull/7#issuecomment-2100777582.

I'll get back to you with the plots

2024-05-13 08:17 UTC, mj-will commented on BBHX_Phenom.py
> +    if log_mf_min is None:
Agreed, I've removed it now.

2024-05-13 13:35 UTC, mj-will commented on BBHX_Phenom.py
> +                m_mode=max_m_mode,
@WuShichao I think this plot is quite helpful

![image](https://github.com/gwastro/BBHX-waveform-model/assets/25609742/f936a283-3422-4a9a-91f8-48e93b0fcb33)

The solid lines are the raw output from BBHx before TDI (this should be comparable to `interpolated_tf`). The dashed lines show the output of `interpolated_tf`. The vertical black lines show the `t_max` values for the 21 and 44 mode and the horizontal lines show the `f_min` computed from the track.

I don't think we want the lowest frequency at a given time, but rather we want the frequency at which to start the waveform generation. If want to be consistent with PyCBC and BBHx, I think this would be the highest mode. That means that e.g. the 21 mode will start later, but that is at least consistent between the code.

2024-05-13 14:24 UTC, mj-will commented
The rebase was going to be a nightmare after the TDi change, so I just merged the changes from main instead.

2024-05-13 17:07 UTC, WuShichao commented on BBHX_Phenom.py
> +                m_mode=max_m_mode,
@mj-will Cool plot! Those solid lines match the dashed lines at the early inspiral part of SMBHB. I believe the frequency to which those dashed lines converge is the `f_isco`. Do you mean solid lines are from `IMRPhenomHM` in LAL or do you modify `BBHx` to plot the intermediate waveform? And the chirp shape is not that clear in this plot. This plot shows the `if t_obs_start < t_max` case, so the plugin will get the `f_min` from the tracks at the given `t_obs_start`, `f_min` from (2,1) is lower, so we need to choose that one, although it's lower than LISA low-f cutoff, maybe we need to add a check for this.

2024-05-13 17:20 UTC, mj-will commented on BBHX_Phenom.py
> +                m_mode=max_m_mode,
@WuShichao the solid lines are directly from the `PhenomHMAmpPhase` class in BBHx.

Tagging @spxiwh so he can chime in on this.

2024-05-13 17:25 UTC, mj-will commented on BBHX_Phenom.py
> +                m_mode=max_m_mode,
> If you choose 1e-4 Hz from (4, 4) at the given t_obs_start, you will ignore the signal components below that (if LISA's low-f cutoff allows it).

And yes, I agree that's what will happen. However, if we set it to a lower value, I believe this would lead to the (4, 4) mode also starting at the lower value, and therefore it would include times before `t_obs_start` (though I may be missing something)

2024-05-13 21:17 UTC, WuShichao commented on BBHX_Phenom.py
> +                m_mode=max_m_mode,
Another question is do you include spins in the solid lines?

2024-05-14 08:11 UTC, mj-will commented on BBHX_Phenom.py
> +                m_mode=max_m_mode,
@WuShichao yes, this particular example was calculated with spins.

For reference, here's the code (note the SOBHB raises an error because of issues with the interpolation ranges):

```python
from bbhx.waveforms.phenomhm import PhenomHMAmpPhase
from BBHX_Phenom import chirptime, interpolated_tf, cached_freq_logspace
import matplotlib.pyplot as plt
import numpy as np
from scipy.interpolate import interp1d

params = {
    "SMBHB": {
        "mass1": 1e6,
        "mass2": 8e5,
        "spin1z": 0.4,
        "spin2z": 0.3,
        "t_obs_start": 31536000,
        "interp_f_lower": 1e-5
    },
    # "SOBHB": {
    #     "mass1": 32.0,
    #     "mass2": 29.0,
    #     "spin1z": 0.4,
    #     "spin2z": 0.3,
    #     "t_obs_start": 315360000,
    #     "interp_f_lower": 1e-7
    # }
}

for label, theta in params.items():
    phenomhm = PhenomHMAmpPhase(use_gpu=False, run_phenomd=False)
    modes = [(2, 2), (2, 1), (3, 3), (3, 2), (4, 4), (4, 3)]
    phenomhm(
        theta["mass1"],
        theta["mass2"],
        theta["spin1z"],
        theta["spin2z"],
        1e20,
        0.0,
        0.0,
        0.0,
        1024,
        modes=modes,
    )
    colours = [f"C{i}" for i in range(len(modes))]
    interp_f_lower = theta["interp_f_lower"]
    num_interp=1000

    plt.title(label)
    
    for i, mode in enumerate(modes):
        times = -phenomhm.tf[0][i][:]
        plt.plot(times, phenomhm.freqs, label=mode, c=colours[i])
        tf_track = interpolated_tf(theta["mass1"], theta["mass2"], m_mode=mode[1], num_interp=num_interp, f_lower=interp_f_lower)
        f_approx = tf_track(times)
        plt.plot(times, f_approx, ls="--", c=colours[i])

    plt.axvline(theta["t_obs_start"], c="navy", ls="-", label="t_obs_start")
    print(f"t_obs_start={theta['t_obs_start']}")

    t_max_44 = chirptime(theta["mass1"], theta["mass1"], f_lower=interp_f_lower, m_mode=4)
    tf_track = interpolated_tf(theta["mass1"], theta["mass2"], m_mode=4, num_interp=num_interp, f_lower=interp_f_lower)
    f_min_44 = tf_track(theta["t_obs_start"])
    print(f"t_max={t_max_44}")
    print(f"f_min (44)={f_min_44}")
    plt.axvline(t_max_44, c="k", ls="-", label="t_max (44)")
    plt.axhline(f_min_44, c="grey", label="f_min (44)")

    t_max_21 = chirptime(theta["mass1"], theta["mass1"], f_lower=interp_f_lower, m_mode=1)
    tf_track = interpolated_tf(theta["mass1"], theta["mass2"], m_mode=1, num_interp=num_interp, f_lower=interp_f_lower)
    f_min_21 = tf_track(theta["t_obs_start"])
    print(f"t_max={t_max_21}")
    print(f"f_min (21)={f_min_21}")
    plt.axvline(t_max_21, c="k", ls=":", label="t_max (21)")
    plt.axhline(f_min_21, c="grey", label="f_min (21)", ls=":")

    plt.xscale("log")
    plt.yscale("log")
    plt.gca().invert_xaxis()
    plt.xlabel("t [s]")
    plt.ylabel("f [Hz]")
    plt.legend()
    plt.show()

```

2024-05-14 14:09 UTC, spxiwh commented on BBHX_Phenom.py
> +                m_mode=max_m_mode,
@WuShichao This is the same issue as in the ground-based generation in PyCBC (as far as I can see). You are choosing a low-frequency cutoff, and figuring out the time needed to properly contain that signal. Remember that BBHx requires a lower *frequency*, and not just a start time.

If I want to determine the duration of my signal from a given f_lower ... Or figure out what f_lower I need to choose given a duration, I need to use the highest m mode. If I base duration on the 2,1 mode, and give BBHx a f_lower based on this, then the 4,4 mode will also be generated down to that f_lower and will wraparound.

I do want to avoid going around and around on this, so how do we get this approved?

2024-05-14 14:32 UTC, WuShichao commented on BBHX_Phenom.py
> +                m_mode=max_m_mode,
> @WuShichao yes, this particular example was calculated with spins.
> 
> For reference, here's the code (note the SOBHB raises an error because of issues with the interpolation ranges):
> 
> ```python
> from bbhx.waveforms.phenomhm import PhenomHMAmpPhase
> from BBHX_Phenom import chirptime, interpolated_tf, cached_freq_logspace
> import matplotlib.pyplot as plt
> import numpy as np
> from scipy.interpolate import interp1d
> 
> params = {
>     "SMBHB": {
>         "mass1": 1e6,
>         "mass2": 8e5,
>         "spin1z": 0.4,
>         "spin2z": 0.3,
>         "t_obs_start": 31536000,
>         "interp_f_lower": 1e-5
>     },
>     # "SOBHB": {
>     #     "mass1": 32.0,
>     #     "mass2": 29.0,
>     #     "spin1z": 0.4,
>     #     "spin2z": 0.3,
>     #     "t_obs_start": 315360000,
>     #     "interp_f_lower": 1e-7
>     # }
> }
> 
> for label, theta in params.items():
>     phenomhm = PhenomHMAmpPhase(use_gpu=False, run_phenomd=False)
>     modes = [(2, 2), (2, 1), (3, 3), (3, 2), (4, 4), (4, 3)]
>     phenomhm(
>         theta["mass1"],
>         theta["mass2"],
>         theta["spin1z"],
>         theta["spin2z"],
>         1e20,
>         0.0,
>         0.0,
>         0.0,
>         1024,
>         modes=modes,
>     )
>     colours = [f"C{i}" for i in range(len(modes))]
>     interp_f_lower = theta["interp_f_lower"]
>     num_interp=1000
> 
>     plt.title(label)
>     
>     for i, mode in enumerate(modes):
>         times = -phenomhm.tf[0][i][:]
>         plt.plot(times, phenomhm.freqs, label=mode, c=colours[i])
>         tf_track = interpolated_tf(theta["mass1"], theta["mass2"], m_mode=mode[1], num_interp=num_interp, f_lower=interp_f_lower)
>         f_approx = tf_track(times)
>         plt.plot(times, f_approx, ls="--", c=colours[i])
> 
>     plt.axvline(theta["t_obs_start"], c="navy", ls="-", label="t_obs_start")
>     print(f"t_obs_start={theta['t_obs_start']}")
> 
>     t_max_44 = chirptime(theta["mass1"], theta["mass1"], f_lower=interp_f_lower, m_mode=4)
>     tf_track = interpolated_tf(theta["mass1"], theta["mass2"], m_mode=4, num_interp=num_interp, f_lower=interp_f_lower)
>     f_min_44 = tf_track(theta["t_obs_start"])
>     print(f"t_max={t_max_44}")
>     print(f"f_min (44)={f_min_44}")
>     plt.axvline(t_max_44, c="k", ls="-", label="t_max (44)")
>     plt.axhline(f_min_44, c="grey", label="f_min (44)")
> 
>     t_max_21 = chirptime(theta["mass1"], theta["mass1"], f_lower=interp_f_lower, m_mode=1)
>     tf_track = interpolated_tf(theta["mass1"], theta["mass2"], m_mode=1, num_interp=num_interp, f_lower=interp_f_lower)
>     f_min_21 = tf_track(theta["t_obs_start"])
>     print(f"t_max={t_max_21}")
>     print(f"f_min (21)={f_min_21}")
>     plt.axvline(t_max_21, c="k", ls=":", label="t_max (21)")
>     plt.axhline(f_min_21, c="grey", label="f_min (21)", ls=":")
> 
>     plt.xscale("log")
>     plt.yscale("log")
>     plt.gca().invert_xaxis()
>     plt.xlabel("t [s]")
>     plt.ylabel("f [Hz]")
>     plt.legend()
>     plt.show()
> ```

Thanks, so that means spin doesn't change the time-frequency track much. According to what @spxiwh said, choose max_m is for avoiding wrap-around effect in the given time duration, then that makes sense.

2024-05-14 14:34 UTC, WuShichao commented
Looks good and reasonable, if you can show the Q-transform of TDI waveform in the call that would be better.

2024-05-14 14:34 UTC, merged